export const SIGNING_IN_USER = 'SIGNING_IN_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_RESET = 'SIGN_IN_RESET';

export const AUTHENTICATED = 'AUTHENTICATED_USER';
export const UNAUTHENTICATED = 'UNAUTHENTICATED_USER';
export const AUTHENTICATED_ERROR = 'AUTHENTICATED_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNINGUP_USER = 'SIGNINGUP_USER';
export const RESET_USER = 'RESET_USER';

export const CREATING_CENTER = 'CREATING_CENTER';
export const CENTER_CREATED_SUCCESS = 'CENTER_CREATED';
export const CENTER_CREATED_FAILURE = 'CENER_ERROR';
export const CENTER_RESET = 'CENTER_RESET';

export const FETCHING_CENTER = 'FETCHING_CENTER';
export const FETCHING_CENTER_SUCCESS = 'FETCHING_CENTER_SUCCESS';
export const FETCHING_CENTER_ERROR = 'FETCHING_CENTER_SUCCESS';

export const UPDATING_CENTER = 'UPDATING_CENTER';
export const UPDATING_CENTER_SUCCESS = 'UPDATING_CENTER_SUCCESS';
export const UPDATING_CENTER_FAILURE = 'UPDATING_CENTER_FAILURE';

export const CENTER_DELETED = 'CENTER_DELETED';
export const CENTER_DELETING = 'CENTER_DELETING';

export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const FETCH_CENTER_EVENT_SUCCESS = 'FETCH_CENTER_EVENT_SUCCESS';
export const FETCH_CENTER_EVENT_FAILURE = 'FETCH_CENTER_EVENT_FAILURE';
export const FETCHING_CENTER_EVENT = 'FETCHING_CENTER_EVENT';

export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';
export const CREATING_EVENT = 'CREATING_EVENT';
export const RESET_EVENT = 'RESET_EVENT';

export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';
export const FETCHING_EVENT = 'FETCHING_EVENT';

export const FETCH_EVENT_BY_ID = 'FETCH_EVENT_BY_ID';
export const FETCHING_EVENT_BY_ID = 'FETCHING_EVENT_BY_ID';
export const FETCH_EVENT_BY_ID_FAILURE = 'FETCH_EVENT_BY_ID_FAILURE';
