// sign-in user
export const SIGNING_IN_USER = 'SIGNING_IN_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_RESET = 'SIGN_IN_RESET';

export const AUTHENTICATED = 'AUTHENTICATED_USER';
export const UNAUTHENTICATED = 'UNAUTHENTICATED_USER';
export const AUTHENTICATED_ERROR = 'AUTHENTICATED_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNINGUP_USER = 'SIGNINGUP_USER';
export const RESET_USER = 'RESET_USER';
